server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

